[package]
name = "librax-detection"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
librax-types.workspace = true
librax-mitre.workspace = true

chrono.workspace = true
serde.workspace = true
tracing.workspace = true

[dev-dependencies]
librax-connectors.workspace = true
librax-enrichment.workspace = true
librax-normalizer.workspace = true
